name: AUR Release

on:
  push:
    tags:
      - 'v*'

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Package
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S base-devel --noconfirm
          makepkg -s --noconfirm

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            varchiver-${{ env.VERSION }}-*.pkg.tar.zst
            varchiver-linux-x86_64.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: varchiver
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version ${{ env.VERSION }}" 